name: ci

on: pull_request

jobs:
  autofix:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'steebchen' || github.actor == 'smakosh' }}

    steps:
      - name: Autofix
        uses: steebchen/actions/autofix@v0.14.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          format-command: pnpm generate && pnpm format
